# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Emre Tezel
tagline:          'Personal website'
description:      'Personal website.'
url:              https://e-tezel.github.io/
baseurl:          

author:
  name:           'Emre Tezel'

paginate:         1

# Custom vars
version:          2.1.0

github:
  profile:           https://github.com/e-tezel

linkedin:         https://www.linkedin.com/in/emre-tezel/