# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Emre Tezel
tagline:          ''
description:      'Kişisel web sitesi.'
url:              https://e-tezel.github.io/
baseurl:          

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
